ALTER TABLE shops DROP COLUMN clerk_org_id;
ALTER TABLE shops ADD COLUMN user_id text NOT NULL UNIQUE;

ALTER TABLE users RENAME COLUMN clerk_user_id TO auth_user_id;

DROP TABLE IF EXISTS invitation CASCADE;
DROP TABLE IF EXISTS member CASCADE;
DROP TABLE IF EXISTS organization CASCADE;
DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS verification CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
